name: Frontend CI

on:
  push:
    branches: [ "development", "staging", "production" ]
  pull_request:
    branches: [ "development", "staging", "production" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "18.x"
        cache: "npm"
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm test
    - name: Build
      run: npm run build
